#!/usr/bin/env python3
"""
Minervini SEA (Specific Entry Point Analysis) Strategy
======================================================

Implementation of Mark Minervini's legendary trading methodology based on:
- "Trade Like a Stock Market Wizard"
- "Think and Trade Like a Champion"

Core Principles:
1. Only trade Stage 2 uptrends (wind at your back)
2. Buy high, sell higher (momentum investing)
3. Volatility Contraction Pattern (VCP) for entries
4. Strict risk management (1-2% risk per trade)
5. Cut losses quickly, let winners run

Author: Trading Bot System
Version: 1.0.0
"""

import json
import logging
import sqlite3
import numpy as np
import pandas as pd
from datetime import datetime, timezone, timedelta
from typing import Dict, List, Optional, Any, Tuple
from dataclasses import dataclass, asdict

# Try to import pandas-ta for technical indicators
try:
    import pandas_ta as ta
    PANDAS_TA_AVAILABLE = True
except ImportError:
    PANDAS_TA_AVAILABLE = False
    logging.warning("pandas-ta not available. Using custom indicator calculations.")

logger = logging.getLogger(__name__)


@dataclass
class VCPPattern:
    """Represents a detected Volatility Contraction Pattern"""
    valid: bool
    pivot_price: float
    stop_loss: float
    contractions: List[Dict[str, float]]  # List of {depth: %, width: bars}
    base_high: float
    base_low: float
    volume_dry_up: bool
    tightness_score: float  # 0-100, higher is tighter
    
    def __repr__(self):
        if not self.valid:
            return "VCP(invalid)"
        return f"VCP(pivot=${self.pivot_price:.2f}, stop=${self.stop_loss:.2f}, tightness={self.tightness_score:.1f})"


@dataclass
class TrendTemplate:
    """Minervini's Trend Template criteria"""
    close_above_150sma: bool
    close_above_200sma: bool
    sma150_above_sma200: bool
    sma200_rising: bool
    within_25pct_of_52wh: bool
    rs_rating: float
    
    @property
    def all_passed(self) -> bool:
        """Check if all trend template criteria are met"""
        return (
            self.close_above_150sma and
            self.close_above_200sma and
            self.sma150_above_sma200 and
            self.sma200_rising and
            self.within_25pct_of_52wh and
            self.rs_rating >= 70  # Minervini prefers 80-90
        )
    
    def to_dict(self) -> Dict:
        return {
            "close_above_150sma": self.close_above_150sma,
            "close_above_200sma": self.close_above_200sma,
            "sma150_above_sma200": self.sma150_above_sma200,
            "sma200_rising": self.sma200_rising,
            "within_25pct_of_52wh": self.within_25pct_of_52wh,
            "rs_rating": self.rs_rating,
            "all_passed": self.all_passed
        }


@dataclass
class SEASignal:
    """Signal generated by Minervini SEA strategy"""
    timestamp: str
    symbol: str
    side: str  # 'buy', 'sell', 'hold'
    confidence: float
    reason: str
    entry_price: Optional[float] = None
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    position_size: Optional[int] = None
    risk_per_share: Optional[float] = None
    vcp_pattern: Optional[VCPPattern] = None
    trend_template: Optional[TrendTemplate] = None
    metadata: Dict = None


@dataclass
class SEATrade:
    """Executed SEA trade record"""
    trade_id: str
    timestamp: str
    symbol: str
    side: str
    shares: int
    entry_price: float
    stop_loss: float
    initial_stop: float
    risk_amount: float
    status: str  # 'open', 'closed'
    pnl: float = 0.0
    pnl_pct: float = 0.0
    exit_price: Optional[float] = None
    exit_reason: Optional[str] = None
    trailing_stop_activated: bool = False
    metadata: Dict = None


class MinerviniSEAStrategy:
    """
    Mark Minervini's SEA (Specific Entry Point Analysis) Strategy
    
    This is a pure rule-based momentum strategy that:
    1. Filters for Stage 2 uptrend stocks (Trend Template)
    2. Waits for Volatility Contraction Pattern (VCP) setup
    3. Enters on high-volume breakout above VCP pivot
    4. Uses strict position sizing (1-2% risk per trade)
    5. Trims losses quickly (7-8% stop loss)
    6. Lets winners run with trailing stops
    
    Expected Performance:
    - Win rate: 30-40% (yes, most trades lose!)
    - Reward/Risk: 3:1 to 10:1 on winners
    - Expect 60-70% losing trades but winners compensate
    """
    
    def __init__(self, config: Dict[str, Any]):
        """
        Initialize Minervini SEA Strategy
        
        Args:
            config: Strategy configuration with keys:
                - name: Strategy name
                - enabled: Whether strategy is active
                - account_size: Total account size in USD
                - risk_per_trade: Risk percentage per trade (default 1.0)
                - max_position_usd: Maximum position size in USD
                - min_rs_rating: Minimum Relative Strength rating (default 70)
                - vcp_min_contractions: Minimum contractions in VCP (default 2)
                - vcp_max_total_depth: Maximum total VCP depth % (default 30)
                - volume_surge_ratio: Volume surge required for breakout (default 1.4)
                - trailing_stop_activation: Profit level to activate trailing stop (default 2.5)
        """
        self.config = config
        self.name = config.get("name", "Minervini_SEA")
        self.enabled = config.get("enabled", True)
        
        # Account and risk parameters (Rule #5: 1-2% risk per trade)
        self.account_size = config.get("account_size", 100000)
        self.risk_per_trade = config.get("risk_per_trade", 1.0)  # 1% default
        self.max_position_usd = config.get("max_position_usd", 10000)
        
        # Trend Template parameters
        self.min_rs_rating = config.get("min_rs_rating", 70)
        self.max_distance_from_52wh = config.get("max_distance_from_52wh", 0.25)  # 25%
        
        # VCP parameters
        self.vcp_min_contractions = config.get("vcp_min_contractions", 2)
        self.vcp_max_total_depth = config.get("vcp_max_total_depth", 0.30)  # 30%
        self.vcp_min_tightness_score = config.get("vcp_min_tightness_score", 60)
        
        # Entry/Exit parameters
        self.volume_surge_ratio = config.get("volume_surge_ratio", 1.4)  # 40% above avg
        self.initial_stop_pct = config.get("initial_stop_pct", 0.07)  # 7-8% from transcript
        self.trailing_stop_activation = config.get("trailing_stop_activation", 2.5)  # 2.5x risk
        
        # State tracking
        self.signals: List[SEASignal] = []
        self.trades: List[SEATrade] = []
        self.open_trades: Dict[str, SEATrade] = {}  # symbol -> trade
        
        # Statistics
        self.stats = {
            "total_scans": 0,
            "trend_template_passed": 0,
            "vcp_detected": 0,
            "signals_generated": 0,
            "trades_executed": 0,
            "trades_exited": 0,
            "wins": 0,
            "losses": 0,
            "total_pnl": 0.0,
            "avg_win_pct": 0.0,
            "avg_loss_pct": 0.0
        }
        
        self._init_database()
        logger.info(f"[{self.name}] Minervini SEA Strategy initialized")
        logger.info(f"[{self.name}] Account: ${self.account_size:,.2f}, Risk: {self.risk_per_trade}%")
    
    def _init_database(self):
        """Initialize database tables for this strategy"""
        conn = sqlite3.connect("trades.db")
        
        # Trades table
        conn.execute(f"""
            CREATE TABLE IF NOT EXISTS strategy_{self.name.lower()}_trades (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                trade_id TEXT UNIQUE,
                timestamp TEXT,
                symbol TEXT,
                side TEXT,
                shares INTEGER,
                entry_price REAL,
                stop_loss REAL,
                initial_stop REAL,
                risk_amount REAL,
                status TEXT,
                exit_price REAL,
                exit_reason TEXT,
                pnl REAL,
                pnl_pct REAL,
                metadata TEXT
            )
        """)
        
        # Signals table
        conn.execute(f"""
            CREATE TABLE IF NOT EXISTS strategy_{self.name.lower()}_signals (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                timestamp TEXT,
                symbol TEXT,
                side TEXT,
                confidence REAL,
                reason TEXT,
                entry_price REAL,
                stop_loss REAL,
                metadata TEXT
            )
        """)
        
        conn.commit()
        conn.close()
    
    def calculate_relative_strength(
        self,
        df: pd.DataFrame,
        benchmark_df: Optional[pd.DataFrame] = None,
        lookback_days: int = 252  # ~1 year of trading days
    ) -> float:
        """
        Calculate Relative Strength (RS) rating
        
        From transcript: "Relative Strength (RS) rating ≥ 70 (preferably 80-90)"
        
        Method: Compare stock's 12-month return to benchmark (SPY)
        RS = (stock_return / benchmark_return) * 100
        
        If no benchmark provided, uses percentile rank within universe
        
        Args:
            df: Stock price DataFrame with 'close' column
            benchmark_df: Benchmark index DataFrame (e.g., SPY)
            lookback_days: Period for RS calculation
            
        Returns:
            RS rating (0-100 scale)
        """
        if len(df) < lookback_days:
            return 0.0
        
        # Calculate stock return
        recent_close = df['close'].iloc[-1]
        past_close = df['close'].iloc[-lookback_days]
        stock_return = (recent_close - past_close) / past_close
        
        if benchmark_df is not None and len(benchmark_df) >= lookback_days:
            # Calculate benchmark return
            bench_recent = benchmark_df['close'].iloc[-1]
            bench_past = benchmark_df['close'].iloc[-lookback_days]
            benchmark_return = (bench_recent - bench_past) / bench_past
            
            # RS = (stock_return / benchmark_return) * 100
            if benchmark_return != 0:
                rs = (stock_return / benchmark_return) * 100
                # Normalize to 0-100 scale (typical range 0-200)
                rs_rating = min(100, max(0, rs))
                return rs_rating
        
        # Fallback: Use percentile rank if no benchmark
        # This would require universe data - simplified here
        return 50.0  # Neutral if can't calculate
    
    def check_trend_template(
        self,
        df: pd.DataFrame,
        benchmark_df: Optional[pd.DataFrame] = None
    ) -> TrendTemplate:
        """
        Check Minervini's Trend Template (Stage 2 filter)
        
        From transcript:
        1. Close > 150-day SMA and > 200-day SMA
        2. 150-day SMA > 200-day SMA
        3. 200-day SMA has been rising for at least 4 months (120 trading days)
        4. Current price within 25% of 52-week high
        5. Relative Strength rating ≥ 70
        
        This eliminates ~90% of stocks (only trade the best)
        
        Args:
            df: Stock DataFrame with OHLCV data
            benchmark_df: Benchmark for RS calculation
            
        Returns:
            TrendTemplate with all criteria checked
        """
        if len(df) < 252:  # Need at least 1 year of data
            return TrendTemplate(
                close_above_150sma=False,
                close_above_200sma=False,
                sma150_above_sma200=False,
                sma200_rising=False,
                within_25pct_of_52wh=False,
                rs_rating=0
            )
        
        # Calculate moving averages
        df['sma150'] = df['close'].rolling(window=150).mean()
        df['sma200'] = df['close'].rolling(window=200).mean()
        
        latest = df.iloc[-1]
        close = latest['close']
        sma150 = latest['sma150']
        sma200 = latest['sma200']
        
        # 1. Close > 150-day SMA and > 200-day SMA
        close_above_150sma = close > sma150
        close_above_200sma = close > sma200
        
        # 2. 150-day SMA > 200-day SMA
        sma150_above_sma200 = sma150 > sma200
        
        # 3. 200-day SMA rising for 120 days
        # Check if SMA200 today > SMA200 120 days ago
        sma200_120_days_ago = df['sma200'].iloc[-120]
        sma200_rising = sma200 > sma200_120_days_ago
        
        # 4. Current price within 25% of 52-week high
        high_52w = df['high'].rolling(window=252).max().iloc[-1]
        distance_from_high = (high_52w - close) / high_52w
        within_25pct_of_52wh = distance_from_high <= self.max_distance_from_52wh
        
        # 5. Relative Strength rating
        rs_rating = self.calculate_relative_strength(df, benchmark_df)
        
        return TrendTemplate(
            close_above_150sma=close_above_150sma,
            close_above_200sma=close_above_200sma,
            sma150_above_sma200=sma150_above_sma200,
            sma200_rising=sma200_rising,
            within_25pct_of_52wh=within_25pct_of_52wh,
            rs_rating=rs_rating
        )
    
    def detect_vcp(self, df: pd.DataFrame, lookback_days: int = 60) -> VCPPattern:
        """
        Detect Volatility Contraction Pattern (VCP)
        
        From transcript:
        - Stock already in strong uptrend (Stage 2)
        - Series of 3+ pullbacks where each contraction is smaller:
          * First pullback: ~20-28% range
          * Second: ~12-16%
          * Third: ≤6-8% (tighter the better)
        - Volume dries up during contractions
        - Final tightest consolidation near the highs
        - Breakout = close > VCP high on volume ≥40-50% above avg
        
        This is the "coiled spring" setup that precedes explosive moves.
        
        Algorithm:
        1. Find significant swing highs and lows in recent period
        2. Measure depth of each pullback from recent high
        3. Check if contractions are getting smaller (volatility compression)
        4. Verify volume is declining during consolidation
        5. Identify pivot point (tightest area near highs)
        
        Args:
            df: Stock DataFrame with OHLCV data
            lookback_days: Period to look for VCP pattern
            
        Returns:
            VCPPattern with detection results
        """
        if len(df) < lookback_days:
            return VCPPattern(valid=False, pivot_price=0, stop_loss=0, 
                            contractions=[], base_high=0, base_low=0,
                            volume_dry_up=False, tightness_score=0)
        
        # Get recent data
        recent = df.tail(lookback_days).copy()
        
        # Find the highest high in the period (start of consolidation)
        base_high = recent['high'].max()
        base_high_idx = recent['high'].idxmax()
        
        # Get data from the high point onwards (the consolidation)
        consolidation = recent.loc[base_high_idx:].copy()
        
        if len(consolidation) < 10:  # Need at least 10 days of consolidation
            return VCPPattern(valid=False, pivot_price=0, stop_loss=0,
                            contractions=[], base_high=0, base_low=0,
                            volume_dry_up=False, tightness_score=0)
        
        # Find swing lows (potential contraction points)
        consolidation['swing_low'] = consolidation['low'][
            (consolidation['low'].shift(1) > consolidation['low']) &
            (consolidation['low'].shift(-1) > consolidation['low'])
        ]
        
        swing_lows = consolidation.dropna(subset=['swing_low'])
        
        if len(swing_lows) < 2:
            return VCPPattern(valid=False, pivot_price=0, stop_loss=0,
                            contractions=[], base_high=0, base_low=0,
                            volume_dry_up=False, tightness_score=0)
        
        # Calculate contractions (depth from base high)
        contractions = []
        for idx, row in swing_lows.iterrows():
            depth = (base_high - row['swing_low']) / base_high
            contractions.append({
                'date': idx,
                'price': row['swing_low'],
                'depth': depth,
                'width': 0  # Will calculate later
            })
        
        # Need at least 2 contractions
        if len(contractions) < self.vcp_min_contractions:
            return VCPPattern(valid=False, pivot_price=0, stop_loss=0,
                            contractions=[], base_high=0, base_low=0,
                            volume_dry_up=False, tightness_score=0)
        
        # Check if contractions are getting smaller (volatility compression)
        # First should be deepest, last should be shallowest
        first_depth = contractions[0]['depth']
        last_depth = contractions[-1]['depth']
        
        # Minervini criteria: first ~20-28%, second ~12-16%, third ≤6-8%
        valid_pattern = (
            first_depth <= self.vcp_max_total_depth and  # Not too deep overall
            last_depth < first_depth * 0.6  # Last is at least 40% shallower
        )
        
        if not valid_pattern:
            return VCPPattern(valid=False, pivot_price=0, stop_loss=0,
                            contractions=contractions, base_high=base_high,
                            base_low=consolidation['low'].min(),
                            volume_dry_up=False, tightness_score=0)
        
        # Check volume dry-up
        # Volume should be decreasing or below average during consolidation
        avg_volume = df['volume'].tail(50).mean()
        recent_volume = consolidation.tail(10)['volume'].mean()
        volume_dry_up = recent_volume < avg_volume * 0.8  # 20% below avg
        
        # Calculate tightness score (0-100)
        # Based on how tight the last contraction is
        tightness = 1 - (last_depth / 0.10)  # 10% depth = 0 score, 0% = 100
        tightness_score = max(0, min(100, tightness * 100))
        
        # Find pivot area (tightest consolidation near highs)
        # Last 5 days should be within tight range
        last_5 = consolidation.tail(5)
        pivot_high = last_5['high'].max()
        pivot_low = last_5['low'].min()
        pivot_range = (pivot_high - pivot_low) / pivot_high
        
        # Pivot should be very tight (<5% range)
        is_tight_pivot = pivot_range < 0.05
        
        if not is_tight_pivot:
            tightness_score *= 0.5  # Penalize loose pivot
        
        # Calculate stop loss (just below lowest contraction)
        lowest_low = min(c['price'] for c in contractions)
        stop_loss = lowest_low * 0.99  # 1% below the low
        
        return VCPPattern(
            valid=tightness_score >= self.vcp_min_tightness_score,
            pivot_price=pivot_high,
            stop_loss=stop_loss,
            contractions=contractions,
            base_high=base_high,
            base_low=consolidation['low'].min(),
            volume_dry_up=volume_dry_up,
            tightness_score=tightness_score
        )
    
    def calculate_position_size(
        self,
        entry_price: float,
        stop_loss: float
    ) -> Tuple[int, float, float]:
        """
        Calculate position size based on 1-2% risk rule
        
        From transcript:
        "If you have $100,000 and risk 1%, max loss is $1,000.
        If entry is $50 and stop is $46, risk per share is $4.
        Max shares = $1,000 / $4 = 250 shares."
        
        Args:
            entry_price: Planned entry price
            stop_loss: Stop loss price
            
        Returns:
            Tuple of (shares, risk_per_share, total_risk)
        """
        risk_amount = self.account_size * (self.risk_per_trade / 100)
        risk_per_share = entry_price - stop_loss
        
        if risk_per_share <= 0:
            return 0, 0, 0
        
        shares = int(risk_amount / risk_per_share)
        
        # Cap position size
        position_value = shares * entry_price
        if position_value > self.max_position_usd:
            shares = int(self.max_position_usd / entry_price)
        
        total_risk = shares * risk_per_share
        
        return shares, risk_per_share, total_risk
    
    def check_entry_signal(
        self,
        df: pd.DataFrame,
        benchmark_df: Optional[pd.DataFrame] = None
    ) -> Optional[SEASignal]:
        """
        Check for entry signal based on Minervini's rules
        
        Entry Rules:
        1. Trend Template must pass (Stage 2)
        2. Valid VCP pattern detected
        3. Price breaks above VCP pivot on volume surge
        
        Args:
            df: Stock DataFrame
            benchmark_df: Market benchmark DataFrame
            
        Returns:
            SEASignal if entry triggered, None otherwise
        """
        if len(df) < 252:
            return None
        
        # 1. Check Trend Template (Stage 2 filter)
        trend = self.check_trend_template(df, benchmark_df)
        if not trend.all_passed:
            return None
        
        self.stats["trend_template_passed"] += 1
        
        # 2. Detect VCP pattern
        vcp = self.detect_vcp(df)
        if not vcp.valid:
            return None
        
        self.stats["vcp_detected"] += 1
        
        # 3. Check for breakout
        latest = df.iloc[-1]
        prev = df.iloc[-2]
        
        # Breakout: Close > VCP pivot price
        price_above_pivot = latest['close'] > vcp.pivot_price
        
        # Volume surge: Volume >= 40-50% above average
        avg_volume = df['volume'].tail(50).mean()
        volume_surge = latest['volume'] >= avg_volume * self.volume_surge_ratio
        
        # Previous day was below pivot (confirms breakout)
        was_below_pivot = prev['close'] <= vcp.pivot_price
        
        if price_above_pivot and volume_surge and was_below_pivot:
            # Calculate position sizing
            entry_price = latest['close']
            shares, risk_per_share, total_risk = self.calculate_position_size(
                entry_price, vcp.stop_loss
            )
            
            if shares <= 0:
                return None
            
            # Calculate take profit (3:1 reward/risk minimum)
            take_profit = entry_price + (risk_per_share * 3)
            
            confidence = min(1.0, vcp.tightness_score / 100 + 0.3)
            
            return SEASignal(
                timestamp=datetime.now(timezone.utc).isoformat(),
                symbol=df.index.name if hasattr(df, 'index') else "UNKNOWN",
                side="buy",
                confidence=confidence,
                reason=f"VCP Breakout: {len(vcp.contractions)} contractions, "
                       f"tightness {vcp.tightness_score:.1f}, "
                       f"volume surge {latest['volume']/avg_volume:.1f}x",
                entry_price=entry_price,
                stop_loss=vcp.stop_loss,
                take_profit=take_profit,
                position_size=shares,
                risk_per_share=risk_per_share,
                vcp_pattern=vcp,
                trend_template=trend,
                metadata={
                    "trend_template": trend.to_dict(),
                    "vcp_contractions": len(vcp.contractions),
                    "vcp_tightness": vcp.tightness_score,
                    "volume_surge": latest['volume'] / avg_volume,
                    "rs_rating": trend.rs_rating
                }
            )
        
        return None
    
    def check_exit_signal(
        self,
        df: pd.DataFrame,
        trade: SEATrade
    ) -> Optional[SEASignal]:
        """
        Check for exit signal (stop loss or trailing stop)
        
        Exit Rules:
        1. Initial stop: 7-8% below entry (fixed)
        2. Trailing stop: Activate at 2.5x profit, move to breakeven + buffer
        3. Hard stop: Close below 200-day SMA
        
        Args:
            df: Stock DataFrame
            trade: Open trade to check
            
        Returns:
            SEASignal if exit triggered, None otherwise
        """
        if len(df) < 200:
            return None
        
        latest = df.iloc[-1]
        close = latest['close']
        low = latest['low']
        sma200 = df['close'].rolling(window=200).mean().iloc[-1]
        
        # Calculate current P&L
        pnl_pct = (close - trade.entry_price) / trade.entry_price
        
        # 1. Check initial stop loss (hard stop)
        if low <= trade.initial_stop:
            return SEASignal(
                timestamp=datetime.now(timezone.utc).isoformat(),
                symbol=trade.symbol,
                side="sell",
                confidence=1.0,
                reason=f"Stop loss hit at ${trade.initial_stop:.2f}",
                exit_price=trade.initial_stop,
                metadata={"exit_type": "stop_loss", "pnl_pct": pnl_pct}
            )
        
        # 2. Check if below 200-day SMA (trend change)
        if close < sma200:
            return SEASignal(
                timestamp=datetime.now(timezone.utc).isoformat(),
                symbol=trade.symbol,
                side="sell",
                confidence=0.9,
                reason=f"Close below 200-day SMA (${sma200:.2f})",
                exit_price=close,
                metadata={"exit_type": "trend_change", "pnl_pct": pnl_pct}
            )
        
        # 3. Trailing stop logic
        # Activate when profit reaches 2.5x initial risk
        initial_risk_pct = (trade.entry_price - trade.initial_stop) / trade.entry_price
        profit_target_pct = initial_risk_pct * self.trailing_stop_activation
        
        if pnl_pct >= profit_target_pct and not trade.trailing_stop_activated:
            # Move stop to breakeven + small buffer
            new_stop = trade.entry_price * 1.02  # 2% profit locked
            trade.stop_loss = new_stop
            trade.trailing_stop_activated = True
            logger.info(f"[{self.name}] Trailing stop activated for {trade.symbol} "
                       f"at ${new_stop:.2f} (current: ${close:.2f})")
        
        # Check trailing stop
        if trade.trailing_stop_activated and low <= trade.stop_loss:
            return SEASignal(
                timestamp=datetime.now(timezone.utc).isoformat(),
                symbol=trade.symbol,
                side="sell",
                confidence=1.0,
                reason=f"Trailing stop hit at ${trade.stop_loss:.2f}",
                exit_price=trade.stop_loss,
                metadata={"exit_type": "trailing_stop", "pnl_pct": pnl_pct}
            )
        
        return None
    
    def scan_symbol(
        self,
        symbol: str,
        df: pd.DataFrame,
        benchmark_df: Optional[pd.DataFrame] = None
    ) -> List[SEASignal]:
        """
        Scan a single symbol for entry/exit signals
        
        Args:
            symbol: Stock symbol
            df: Price DataFrame
            benchmark_df: Market benchmark DataFrame
            
        Returns:
            List of signals
        """
        signals = []
        
        # Check if we have an open trade for this symbol
        if symbol in self.open_trades:
            trade = self.open_trades[symbol]
            exit_signal = self.check_exit_signal(df, trade)
            if exit_signal:
                signals.append(exit_signal)
        else:
            # Look for entry
            entry_signal = self.check_entry_signal(df, benchmark_df)
            if entry_signal:
                signals.append(entry_signal)
        
        return signals
    
    def scan(
        self,
        data: Dict[str, pd.DataFrame],
        benchmark_df: Optional[pd.DataFrame] = None
    ) -> List[SEASignal]:
        """
        Scan multiple symbols for trading opportunities
        
        Args:
            data: Dictionary of symbol -> DataFrame
            benchmark_df: Market benchmark DataFrame (e.g., SPY)
            
        Returns:
            List of SEASignal objects
        """
        self.stats["total_scans"] += 1
        all_signals = []
        
        for symbol, df in data.items():
            try:
                signals = self.scan_symbol(symbol, df, benchmark_df)
                all_signals.extend(signals)
            except Exception as e:
                logger.error(f"[{self.name}] Error scanning {symbol}: {e}")
        
        self.signals.extend(all_signals)
        self.stats["signals_generated"] += len(all_signals)
        
        return all_signals
    
    def execute(self, signal: SEASignal, mode: str = "PAPER") -> Optional[SEATrade]:
        """
        Execute a trade based on signal
        
        Args:
            signal: SEASignal to execute
            mode: 'PAPER' or 'LIVE'
            
        Returns:
            SEATrade record
        """
        if signal.side == "buy":
            return self._execute_entry(signal, mode)
        elif signal.side == "sell":
            return self._execute_exit(signal, mode)
        return None
    
    def _execute_entry(self, signal: SEASignal, mode: str) -> SEATrade:
        """Execute entry (buy) order"""
        trade_id = f"SEA_{datetime.now(timezone.utc).strftime('%Y%m%d%H%M%S')}_{signal.symbol.replace('/', '_')}"
        
        trade = SEATrade(
            trade_id=trade_id,
            timestamp=datetime.now(timezone.utc).isoformat(),
            symbol=signal.symbol,
            side="buy",
            shares=signal.position_size or 0,
            entry_price=signal.entry_price or 0,
            stop_loss=signal.stop_loss or 0,
            initial_stop=signal.stop_loss or 0,
            risk_amount=signal.risk_per_share * signal.position_size if signal.risk_per_share and signal.position_size else 0,
            status="OPEN",
            trailing_stop_activated=False,
            metadata=signal.metadata
        )
        
        self.open_trades[signal.symbol] = trade
        self.trades.append(trade)
        self.stats["trades_executed"] += 1
        
        self._save_trade(trade)
        
        logger.info(f"[{self.name}] BUY {trade.shares} shares of {signal.symbol} "
                   f"@ ${trade.entry_price:.2f}, stop @ ${trade.stop_loss:.2f}")
        
        return trade
    
    def _execute_exit(self, signal: SEASignal, mode: str) -> Optional[SEATrade]:
        """Execute exit (sell) order"""
        if signal.symbol not in self.open_trades:
            return None
        
        trade = self.open_trades[signal.symbol]
        exit_price = signal.exit_price or signal.entry_price or trade.entry_price
        
        # Calculate P&L
        trade.pnl = (exit_price - trade.entry_price) * trade.shares
        trade.pnl_pct = (exit_price - trade.entry_price) / trade.entry_price * 100
        trade.exit_price = exit_price
        trade.exit_reason = signal.reason
        trade.status = "CLOSED"
        
        # Update stats
        if trade.pnl > 0:
            self.stats["wins"] += 1
            self.stats["avg_win_pct"] = (
                (self.stats["avg_win_pct"] * (self.stats["wins"] - 1) + trade.pnl_pct) 
                / self.stats["wins"]
            )
        else:
            self.stats["losses"] += 1
            self.stats["avg_loss_pct"] = (
                (self.stats["avg_loss_pct"] * (self.stats["losses"] - 1) + trade.pnl_pct)
                / self.stats["losses"]
            )
        
        self.stats["total_pnl"] += trade.pnl
        self.stats["trades_exited"] += 1
        
        del self.open_trades[signal.symbol]
        
        self._save_trade(trade)
        
        logger.info(f"[{self.name}] SELL {trade.shares} shares of {signal.symbol} "
                   f"@ ${exit_price:.2f}, P&L: ${trade.pnl:,.2f} ({trade.pnl_pct:+.2f}%)")
        
        return trade
    
    def _save_trade(self, trade: SEATrade):
        """Save trade to database"""
        try:
            conn = sqlite3.connect("trades.db")
            conn.execute(f"""
                INSERT OR REPLACE INTO strategy_{self.name.lower()}_trades
                (trade_id, timestamp, symbol, side, shares, entry_price, 
                 stop_loss, initial_stop, risk_amount, status, exit_price,
                 exit_reason, pnl, pnl_pct, metadata)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """, (
                trade.trade_id, trade.timestamp, trade.symbol, trade.side,
                trade.shares, trade.entry_price, trade.stop_loss, trade.initial_stop,
                trade.risk_amount, trade.status, trade.exit_price, trade.exit_reason,
                trade.pnl, trade.pnl_pct,
                json.dumps(trade.metadata) if trade.metadata else "{}"
            ))
            conn.commit()
            conn.close()
        except Exception as e:
            logger.error(f"[{self.name}] Error saving trade: {e}")
    
    def get_stats(self) -> Dict:
        """Get strategy statistics"""
        total_trades = self.stats["wins"] + self.stats["losses"]
        win_rate = (self.stats["wins"] / total_trades * 100) if total_trades > 0 else 0
        
        # Calculate profit factor
        gross_profit = self.stats["wins"] * self.stats["avg_win_pct"] if self.stats["wins"] > 0 else 0
        gross_loss = abs(self.stats["losses"] * self.stats["avg_loss_pct"]) if self.stats["losses"] > 0 else 1
        profit_factor = gross_profit / gross_loss if gross_loss > 0 else 0
        
        return {
            **self.stats,
            "win_rate": win_rate,
            "profit_factor": profit_factor,
            "open_trades": len(self.open_trades),
            "avg_trade_pnl": self.stats["total_pnl"] / total_trades if total_trades > 0 else 0
        }
    
    def get_open_positions(self) -> List[SEATrade]:
        """Get list of open trades"""
        return list(self.open_trades.values())


# Example usage and testing
if __name__ == "__main__":
    # Example configuration
    config = {
        "name": "Minervini_SEA",
        "enabled": True,
        "account_size": 100000,
        "risk_per_trade": 1.0,
        "max_position_usd": 10000,
        "min_rs_rating": 70,
        "vcp_min_contractions": 2,
        "vcp_max_total_depth": 0.30,
        "volume_surge_ratio": 1.4,
        "trailing_stop_activation": 2.5
    }
    
    # Initialize strategy
    strategy = MinerviniSEAStrategy(config)
    
    print("Minervini SEA Strategy Initialized")
    print(f"Account Size: ${config['account_size']:,}")
    print(f"Risk per Trade: {config['risk_per_trade']}%")
    print(f"Expected Win Rate: 30-40% (most trades will lose!)")
    print(f"Expected Reward/Risk: 3:1 to 10:1 on winners")
    print()
    print("To use this strategy:")
    print("1. Load stock data into pandas DataFrames")
    print("2. Call strategy.scan(data_dict, benchmark_df)")
    print("3. Execute signals with strategy.execute(signal)")
    print()
    print("See POLYMARKET_SETUP.md for full documentation")
